Send increase allowance for non native swaps
Wasmswap/wasmswap-interface pull request #225
Opened 2022-05-31 22:42 UTC by sashimi36

2022-05-31 23:09 UTC, ben2x4 requested changes
Making good progress here, added a few thoughts and suggestions.

2022-05-31 23:09 UTC, ben2x4 commented on features/swap/hooks/useTokenSwap.tsx
> +          tokenB,
why do we need info on tokenB here?

2022-05-31 23:09 UTC, ben2x4 commented on services/swap/swapTokenForToken.ts
> +export const swapTokenForToken = async ({
So I think this needs to be more flexible, the current code only lets you swap Token A. When you want to be able to swap tokenA or TokenB.

2022-05-31 23:09 UTC, ben2x4 commented on services/swap/swapTokenForToken.ts
> +export const swapTokenForToken = async ({
technically I think it only worker with TokenB even though we use TokenA in the function signature.

2022-05-31 23:09 UTC, ben2x4 commented on services/swap/swapTokenForToken.ts
> +    return executeSwapWithIncreasedAllowance({
this needs a little more thinking with regards to gas fees. If we are doing a `pass_through_swap` we will need more gas then just a regular swap with an allowance message. we might want to pass the gas fee as an input to this function.

2022-05-31 23:12 UTC, sashimi36 commented on features/swap/hooks/useTokenSwap.tsx
> +          tokenB,
good call

2022-06-04 00:32 UTC, ben2x4 approved these changes
LGTM

2022-06-04 00:32 UTC, merged